### ISSUE TITLE
Sample project restricts direct use of nuget in blazor projects

### ISSUE THREAD

**Issue by 1h-me** [decius999/CleanCodeJN-Generic-Apis#1]
The nuget package is containing the sample project which restricts direct use in a razor and blazor project and results in a compilation error.

Alternative add the `<RazorLangVersion>3.0</RazorLangVersion>` in CleanCodeJN.GenericApis.Sample.csproj like so:
```
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>
```

**Comment by decius999** [comment]
Why is the sample project contained in the nuget package? It shouldn´t - and I think it is not. For using the package on blazor use the package [CleanCodeJN.GenericApis.Abstractions](https://www.nuget.org/packages/CleanCodeJN.GenericApis.Abstractions/). :)

Because on blazor you should only need to use the POCO classes and abstractions (interfaces and so on)

**Comment by 1h-me** [comment]
That fixed it. Thank you :)
